### PR TITLE
Drop support to deprecated Python (<3.6)

### PR DESCRIPTION
**Pull request by jairhenrique**

### CODE REVIEW

**Comment by drgarcia1986** [comment]
Hey @jairhenrique thanks you so much 🚀 !
There's an issue with Boto version, what about solve it in another PR?
And, could you update the changelog?

**Comment by jairhenrique** [comment]
@drgarcia1986 changelog updated.

**Comment by jairhenrique** [comment]
> There's an issue with Boto version, what about solve it in another PR?

I can't reproduce this error local.

**Comment by drgarcia1986** [comment]
hm, maybe this line on travis.yaml?
```
- export BOTO_CONFIG=/dev/null
```

**Comment by jairhenrique** [comment]
> hm, maybe this line on travis.yaml?
> 
> ```
> - export BOTO_CONFIG=/dev/null
> ```

With or without this config tests fail on CI.

**Comment by jairhenrique** [comment]
@drgarcia1986 I change the region name to `sa-east-1` and 🎉  

https://github.com/boto/boto3/issues/125

**Comment by drgarcia1986** [comment]
Awesome! thank you again @jairhenrique

**Pull request merged**
