### PR TITLE
Add required not none and required types functionality

### PR DESCRIPTION
**Pull request by 987poiuytrewq**
Add two special settings

1. Required not none - require certain settings to have a value that is not none

2. Required types - require certain settings to be of a type or be convertible to that type

### CODE REVIEW

**Comment by drgarcia1986** [comment]
Awesome, thank you @987poiuytrewq .
Could you add this new features on changelog with a new entry `[NEXT_RELEASE]` ?

**Comment by drgarcia1986** [comment]
Thank you @987poiuytrewq 🚀

**Comment by 987poiuytrewq** [comment]
Thanks for merging! When do you think it will be released?

**Comment by drgarcia1986** [comment]
@987poiuytrewq [done](https://pypi.org/project/simple-settings/0.14.0/)  ✅

**Pull request merged**
