### PR TITLE
Refs #31 - Do not update special settings key from ENV

### LINKED ISSUE #31: Getting errors when using env var and OVERRIDE_BY_ENV
It seems that the application is stepping on itself when OVERRIDE_BY_ENV is set and an environment var is used to specify the config file location(s).

settings.py
```python
SIMPLE_SETTINGS = {
    'OVERRIDE_BY_ENV': True,
    # 'REQUIRED_SETTINGS': ('API_TOKEN', 'DB_USER'),
    'DYNAMIC_SETTINGS': {'backend': 'consul'}
}

MYVAR='my-value'
```

app.py
```python
from simple_settings import settings

print(settings.MYVAR)
```

Program output:
```
shell$ SIMPLE_SETTINGS='settings' python app.py
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    print(settings.MYVAR)
  File "/Users/hans/workspace/simple-settings/simple_settings/core.py", line 82, in __getattr__
    self.setup()
  File "/Users/hans/workspace/simple-settings/simple_settings/core.py", line 66, in setup
    self._dynamic_reader = get_dynamic_reader(self._dict)
  File "/Users/hans/workspace/simple-settings/simple_settings/dynamic_settings/__init__.py", line 18, in get_dynamic_reader
    settings_dict.get(SPECIAL_SETTINGS_KEY, {}).get(DYNAMIC_SETTINGS_KEY)
AttributeError: 'str' object has no attribute 'get'
```

(The exact line numbers may be slightly off since I'd added some debug print statements in the library.)

### PR DESCRIPTION
**Pull request by hozn**
Pull request that seems to fix #31.  I am not sure if this is correct, though.

### CODE REVIEW

**Comment by drgarcia1986** [comment]
LGTM 👍 
You can write some test for this ?

**Comment by hozn** [comment]
Yes, will do.

**Comment by hozn** [comment]
Test added.  Confirmed that without fix the test would raise exception on setup() call.

**Comment by drgarcia1986** [comment]
Great, thanks 👍

**Pull request merged**
