### PR TITLE
[Proposal] Get the settings on dynamic first

### PR DESCRIPTION
**Pull request by rafaelgotts**
I just changed the logic to first look to dynamic_setting.

To start working with the simple-settings, we need a settings file, but i think that will be common to look more often to the configured dynamic setting.

### CODE REVIEW

**Comment by drgarcia1986** [comment]
Some little points:
- Could you rebase your branch with the master?
- Could you add some tests?
- Could you add an entry on changelog about this change?
- What about update documentation (section about dynamic readers) to describe this behavior?

I have some mixed feelings about that. Hey @jairhenrique what do you think about it?

**Comment by jairhenrique** [comment]
> I have some mixed feelings about that.

Me too.

It's more comfortable to me see centralized, what settings is possible on my environment.

It's open a possibility to set all my settings out of the centralized file, making it difficult the code readability.

**Explicit is better than implicit.** 🤔

**Comment by drgarcia1986** [comment]
Totally agree ☝️

**Comment by rafaelgotts** [comment]
So, i apparently confused the use of this project.

I will try to do a better understand and then, if it still make any sense, we talk about this resource.

Thanks

**Pull request closed without merging**
