### PR TITLE
Create dynamic memcached

### PR DESCRIPTION
**Pull request by rafaelgotts**

### CODE REVIEW

**Comment by rafaelgotts** [comment]
Thank you!
>There's a problem in s3 tests, did you see?

I think is a problem with dependencies. All tests seems to pass after updates

>I think you need to add Memcached as a service on Travis to run tests, what do you think?

Already included.

**Comment by drgarcia1986** [comment]
@rafaelgotts ping... could you solve the conflicts?

**Comment by rafaelgotts** [comment]
> @rafaelgotts ping... could you solve the conflicts?

Sorry for the late response. I'm doing right now

**Comment by drgarcia1986** [comment]
Hi @rafaelgotts I tried to run the tests on my machine and got same errors, so I added a `sleep(0.1)` before `tests/dynamic_settings/test_memcached.py(L105 and L130)` and works fine, maybe there's a delay with Memcached + pymemcache, what do you think about?

**Comment by rafaelgotts** [comment]
@drgarcia1986 i gave up from pymemcached and changed to python-memcached, as a reliable lib used on Django memcached backend.

Now all tests are passing!!

**Comment by JonathanHuot** [comment]
> if it help you, take a look on the diff:
> 
> ```diff
> diff --git a/tests/dynamic_settings/test_memcached.py b/tests/dynamic_settings/test_memcached.py
> index aa35f7d..6ecea24 100644
> --- a/tests/dynamic_settings/test_memcached.py
> +++ b/tests/dynamic_settings/test_memcached.py
> @@ -1,4 +1,6 @@
>  # -*- coding: utf-8 -*-
> +from time import sleep
> +
>  import pytest
>  
>  from simple_settings.core import LazySettings
> @@ -100,6 +102,7 @@ class TestDynamicMemcachedSettings(object):
>          assert settings.SIMPLE_STRING == 'simple'
>  
>          memcached.set('SIMPLE_STRING', 'dynamic')
> +        sleep(0.1)
>          assert settings.SIMPLE_STRING == 'dynamic'
>  
>          settings.configure(SIMPLE_STRING='foo')
> @@ -124,6 +127,7 @@ class TestDynamicMemcachedSettings(object):
>          assert settings.SIMPLE_STRING == 'simple'
>  
>          memcached.set('MYAPP_SIMPLE_STRING', 'dynamic')
> +        sleep(0.1)
>          assert settings.SIMPLE_STRING == 'dynamic'
>  
>          settings.configure(SIMPLE_STRING='foo')
> ```

The default behavior of pymemcache is to be **asynchronous**. So, instead of doing the `sleep`, you can use `set(.., noreply=False)`. See https://pymemcache.readthedocs.io/en/latest/apidoc/pymemcache.client.base.html#pymemcache.client.base.Client.set 

Else, `pymemcache` looks more active compared to `python-memcached`.

**Comment by lfdesousa** [comment]
I have read this a bit fast, more precisely this part:

https://github.com/drgarcia1986/simple-settings/compare/616d768b4494b3ebbfb8f72249370964e416b9cf..120cf0cf810e64297b7ed807d22a76c74fd76734

But from what I can see you are using a Client, so you connect to a specific host/port, what if we have a cluster of Memcached, would this use case be of interest in this implementation?

**Comment by rafaelgotts** [comment]
> Hey, @JonathanHuot great point thank you!
> 
> @rafaelgotts ping, did you readed Jonathan's comment? Sounds great for me.
> But for me, there's no problem with `python-memcached`.
> 
> Tell me what do you think and I'll merge this.

I make some tests with `noreply` options and have no problem. Let's see on travis now.

**Comment by rafaelgotts** [comment]
> @lfdesousa It's a good point, c/c @rafaelgotts
> IMO we need to be able to give to the user the necessary configuration, but we can add another PR after merge this.

I agree with @drgarcia1986 . We can change this in another PR.

**Pull request merged**
